---
title: "Reproduction of results for Example 3"
author: ""
date: ""
output: pdf_document
header-includes:
  - \usepackage{amsmath}
  - \usepackage{graphicx}
  - \usepackage{enumitem}
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=F}
# Function to assign labels to treatments
TreatLabels <- function(X,n)
{
  Treat <- matrix(c(1,rep(0,n-1)),n,1)
  Label <- 1
  for (i in 2:n)
  {
    Label <- Label+1
    Treat[i] <- Label
    for (j in 1:(i-1))
    {
      if(min(as.numeric(X[i,]==X[j,]))==1) Treat[i] <- Treat[j]
    }
    if(Treat[i] < Label) Label <- Label-1
  }
  Treat <- as.matrix(cbind(Treat,X))
  list(Treat=Treat)
}

# Function for DF breakdown
anovaDF <- function(design, oven, batch, oven.batch, Npar, Npar.Runs )
{
  # DF for treatments at stratum Ovens
  design <- design[,-c(1,2)]
  DF_Treat.Ovens <- nlevels(factor(TreatLabels(design[,1:2],N)$Treat[,1]))-1
  
  # Full treatment factor
  Treat <- factor(TreatLabels(design,N)$Treat[,1])
  
  # Anova to extract DF for Treatments estimated at stratum Runs 
  a1 <- anova(lm(y~oven+batch+oven.batch+Treat))
  DF_Treat.Runs=a1[4,1]
  
  # Anova to extract overall DF for Treatments and for PE in all strata
  a2 <- anova(lm(y~Treat+oven+batch+oven.batch))
  
  PE <- as.data.frame(t(a2[,1][-1]))
  names(PE) <- row.names(a2)[-1]
  PE$oven <- ifelse("oven" %in% names(PE), PE$oven, 0)
  if(PE$oven==0) {PE <- cbind(PE[4],PE[1:3])}
  Lack_of_Fit.Ovens <- DF_Treat.Ovens-(Npar-Npar.Runs)
  total.Ovens <- nlevels(oven)-1
  total.Batches <- total.Ovens*(nlevels(batch)-1)
  Lack_of_Fit.Ovens.Runs <- total.Ovens-DF_Treat.Ovens-PE$oven
  
  df <- data.frame(Treat.Ovens=DF_Treat.Ovens, Model.Ovens=Npar-Npar.Runs,
                   lof.Ovens=DF_Treat.Ovens-(Npar-Npar.Runs), lof.Oven.Runs=Lack_of_Fit.Ovens.Runs,
                   lof.Oven.Batch.Runs=(a2[1,1]-DF_Treat.Ovens-DF_Treat.Runs-Lack_of_Fit.Ovens.Runs), 
                   Treat.Runs=DF_Treat.Runs, Model.Runs=Npar.Runs, lof.Runs=(a1[4,1]-Npar.Runs),PE=PE)
  return(df)
}

# Function to calculate D_S and A_S values for given variance component ratios
efficiencyAD <- function(design,model,Npar,sigma)
{
  W <- rep(1,Npar)
  W[6:10] <- 0.25
  W <- W/sum(W)
  design <- as.data.frame(design)
  oven <- factor(design[,1])
  batch <- factor(design[,2])
  Z1 <- model.matrix(~-1+oven)
  Z2 <- model.matrix(~-1+batch)
  Z3 <- model.matrix(~-1+oven:batch)
  design <- design[,-c(1,2)]
  res <- numeric(0)
  for(i in 1:nrow(sigma)){
    sig <- sigma[i,]
    V <- diag(rep(1,N))+sig[1]*(Z1%*%t(Z1))+sig[2]*Z2%*%t(Z2)+sig[3]*Z3%*%t(Z3)
    X <- model.matrix(model, data=design, keep.order=TRUE)
    Vi <- solve(V)
    V <- solve(t(X)%*%Vi%*%X) # 
    d <- exp(sum(log(round(eigen(V[-1,-1], symmetric=TRUE, 
                                 only.values=TRUE)$values, 6)))/Npar)
    
    v <- sum(W*matrix(diag(V)[-1],nc=1))/sum(W)
    res <- rbind(res,c(d,v))
  }
  colnames(res) <- c("D", "A")
  return(res)
}
```

```{r echo=FALSE}
m1 <- 10 # Ovens
m2 <- 3 # Batches
b <- m1*m2
bsize <- 2
oven <- factor(rep(1:m1, rep(m2*bsize,m1)))
batch <- factor(rep(rep(1:m2,rep(bsize,m2)),m1))
oven.batch <- factor(rep(1:b,rep(bsize,b)))
N <- b*bsize
y <- rnorm(N)    # dummy response
# Approximating model in all strata
model <- formula(~ X1+X2+X3+X4+X5+I(X1^2)+I(X2^2)+I(X3^2)+I(X4^2)+I(X5^2)+X1:X2+
                   X1:X3+X1:X4+X1:X5+X2:X3+X2:X4+X2:X5+X3:X4+X3:X5+X4:X5)
Npar <- length(attr(terms(model), "term.labels")) 

# Approximating model in the lower stratum (Runs)
model.Runs <- formula(~X3+X4+X5+I(X3^2)+I(X4^2)+I(X5^2)+
                    X1:X3+X1:X4+X1:X5+X2:X3+X2:X4+X2:X5+X3:X4+X3:X5+X4:X5)
Npar.Runs <- length(attr(terms(model.Runs), "term.labels"))
```


```{r echo=FALSE}
# read design D* (csv file, should give the path)
library(readr)
jmp <- read_delim("EX3_JMP.csv", show_col_types = FALSE)
df_jmp <- suppressWarnings(anovaDF(jmp, oven, batch, oven.batch, Npar, Npar.Runs))
```

```{r echo=FALSE}
# load the MSS designs
load("MSS_D.RData")
D <- MSS_D$Xopt
df_D <- suppressWarnings(anovaDF(D, oven, batch, oven.batch, Npar, Npar.Runs))
load("MSS_DP.RData")
DP <- MSS_DP$Xopt
df_DP <- suppressWarnings(anovaDF(DP, oven, batch, oven.batch, Npar, Npar.Runs))
load("MSS_CP.RData")
CP <- MSS_CP$Xopt
df_CP <- suppressWarnings(anovaDF(CP, oven, batch, oven.batch, Npar, Npar.Runs))
```

\setcounter{table}{2}
```{r, results='asis', echo=FALSE}
# results
df.jmp <- data.frame(t(df_jmp)); df.jmp$id <- colnames(df_jmp)
df.D <- data.frame(t(df_D)); df.D$id <- colnames(df_D)
df.DP <- data.frame(t(df_DP)); df.DP$id <- colnames(df_DP)
df.CP <- data.frame(t(df_CP)); df.CP$id <- colnames(df_CP)
Table3 <- merge(df.jmp,df.D, by.x="id", all=TRUE)
Table3 <- merge(Table3, df.DP, by.x="id", all=TRUE)
Table3 <- merge(Table3, df.CP, by.x="id", all=TRUE)
Table3[is.na(Table3)] <- 0
reorder <- scan(text="11 5 3 2 8 7 1 9 12 6 4 10", what=double())
Table3 <- Table3[reorder,]
library(xtable)
xtable_tab3 <- xtable(Table3, digits=0, caption="Skeleton ANOVA of designs for Example 3")
colnames(xtable_tab3) <- c("Source", "D*", "MSSD","MSSDP","MSSCP")
print(xtable_tab3, caption.placement = "top", sanitize.colnames.function = identity, include.rownames = FALSE, comment = FALSE)
```

```{r, results='asis', echo=FALSE}
# Efficiencies 
sig <- scan(text="1 10 100",what=double())
Sigma <- expand.grid(sig, sig, sig)
Sigma <- Sigma[order(Sigma[,1],Sigma[,2],Sigma[,3]),]
sigma <- as.matrix(Sigma)
colnames(sigma) <- NULL
eff.jmp <- efficiencyAD(jmp, model, Npar, sigma)
eff.D <- efficiencyAD(D, model, Npar, sigma)
eff.DP <- efficiencyAD(DP, model, Npar, sigma)
eff.CP <- efficiencyAD(CP, model, Npar, sigma)
eff <- cbind(eff.jmp, eff.D, eff.DP, eff.CP)
even_indexes<- seq(2,ncol(eff),2)
odd_indexes<- seq(1,ncol(eff),2)
resA <- eff[,even_indexes]
resD <- eff[,odd_indexes]
effD <- round(100*matrix(rep(resD[,2],ncol(resD)),nc=ncol(resD))/resD,2)
effD <- effD[,-2]
effA <- round(100*matrix(rep(resA[,2],ncol(resA)),nc=ncol(resA))/resA,2)
effA <- effA[,-2]
tab <- cbind(Sigma,e1=NA, effD, e2=NA, effA)
library(xtable)
xtable_tabF <- xtable(tab, digits=c(0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2),
                      caption = "(Supp Table F) DS- and Aw-efficiencies, relative to the best fixed-effects D design obtained, given vc ratios, for designs for Example 3.")
colnames(xtable_tabF) <- c("eta1", "eta2", "eta3", "", "D*","MSSDP","MSSCP","", "D*","MSSDP","MSSCP")
print(xtable_tabF, caption.placement = "top", include.rownames = FALSE, comment = FALSE,
      add.to.row = list(
  pos = list(-1),
  command = c("\\multicolumn{3}{c}{}&&\\multicolumn{3}{c}{Ds}&&\\multicolumn{3}{c}{Aw} \\\\  \n")))
```
\setcounter{figure}{5}
```{r, echo=FALSE, fig.cap="Ds and Aw efficiencies, relative to the MSSD design, as function of variance component ratios for designs for Example3."}
d1 <- data.frame(crit="D",eta1=log10(Sigma[,1]),eta2=log10(Sigma[,2]),
                 eta3=(Sigma[,3]),Design=factor(rep(c("D*","MSSDP","MSSCP"),rep(27,3))),eff=c(effD))
d2 <- data.frame(crit="A",eta1=log10(Sigma[,1]),eta2=log10(Sigma[,2]),
                 eta3=(Sigma[,3]),Design=factor(rep(c("D*","MSSDP","MSSCP"),rep(27,3))),eff=c(effA))
d <- rbind(d1, d2)
d <- d[d[,3]==0,]
d$crit <- factor(d$crit, levels = c("D", "A"),
                 labels = c(expression(paste(D[S])),
                            expression(paste(A[w]))))

custom_colors <- c("D*" = "green", "MSSDP" ="pink" , "MSSCP" = "black")
custom_shapes <- c("D*" = 8, "MSSDP" = 15, "MSSCP" = 19)
labels <- c("D*" = expression(D^paste("*")), 
            "MSSDP" = expression(MSS[paste("(", DP, ")"[S])]),
            "MSSCP" = expression(MSS[CP[kappa]]))

library(ggplot2)
ggplot(d, aes(log10(eta3), eff, group = interaction(eta1, Design), color = Design, shape=Design,
              linetype = factor(eta1))) + 
  facet_wrap(~crit, labeller = label_parsed) + 
  geom_point(size=2.5) +
  geom_line() + 
  scale_shape_manual(values = custom_shapes, labels = labels) +
  scale_color_manual(values = custom_colors, labels = labels) +
  labs(title = "", x = expression(log[10](eta[Ovens*Batches])), y = "Efficiency") + 
  scale_x_continuous(breaks = unique(log10(d$eta3))) + 
  guides(color = guide_legend(title = "Design"), 
         shape = guide_legend(title = "Design"),
         linetype = guide_legend(title = expression(log[10](eta[Ovens])))) + 
  theme(axis.line = element_line(colour = "black"), panel.background = element_blank(), 
        legend.key = element_rect(fill = NA, color = NA),
        strip.background = element_rect(colour = NA, fill = NA),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        axis.text = element_text(size = 14),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14),
        strip.text = element_text(size = 14))
```



