---
title: "Reproduction of Results for Example 1"
author: ""
date: ""
output:
  pdf_document:
    keep_tex: true
    fig_caption: true
header-includes:
  - \usepackage{caption}
  - \usepackage{amsmath}
  - \usepackage{graphicx}
  - \usepackage{enumitem}
  - \DeclareCaptionLabelFormat{S}{Table~S#2}
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=F}
# Function to assign labels to treatments
TreatLabels <- function(X, N) {
  # Create a hash for each row
  hashes <- apply(X, 1, function(row) digest(row, algo = "xxhash64"))
  # Assign unique labels based on hash
  Treat <- as.numeric(factor(hashes))
  # Combine labels with original data
  Treat <- cbind(Treat, X)
  list(Treat = Treat)
}

# Function for DF breakdown
anovaDF <- function(design, design.Z, Z1, Z2, Npar)
{
  N <- nrow(design)
  
  # Full treatment factor
  design.Z$Treat <- factor(TreatLabels(design,N)$Treat[,1])
  T  <- model.matrix(~-1+Treat, data=design.Z)
  N_Treat.Full <- rankMatrix(T)[1] # nlevels(design.Z$Treat)
  
  B <- cbind(Z1,Z2)
  F <- cbind(B,T)
  
  # Runs: Days*Times
  DF_Treat.Runs <- rankMatrix(F)[1] - rankMatrix(B)[1]
  PE.Runs <- N - rankMatrix(F)[1]
  LOF.Runs <- DF_Treat.Runs-Npar
  
  # Days
  total.Day <- nlevels(design.Z$Day)-1
  PE.Day <- rankMatrix(cbind(T,Z1,Z2))[1]-rankMatrix(cbind(T,Z2))[1]
  LOF.Day.Treat_in_Runs <- total.Day-PE.Day
  
  # Times
  total.Time <- nlevels(design.Z$Time)-1
  PE.Time <- rankMatrix(cbind(T,Z1,Z2))[1]-rankMatrix(cbind(T,Z1))[1]
  LOF.Time.Treat_in_Runs <- total.Time-PE.Time
  
  # DF treat as sums
  df_Treat.Full=(DF_Treat.Runs+LOF.Day.Treat_in_Runs+LOF.Time.Treat_in_Runs)
  
  # Equivalent with anova 
  # y <- rnorm(N)    # dummy response
  # PE in Days & Days*Times
  # a1 <- anova(lm(y~Treat+Time+Day, data=design.Z));
  # PE.Day=ifelse("Day" %in% rownames(a1), a1[rownames(a1)=="Day",1], 0)
  # PE.Runs=a1[rownames(a1)=="Residuals",1]
  
  # PE in Times
  # a2 <- anova(lm(y~Treat+Day+Time, data=design.Z));
  # PE.Time=ifelse("Period" %in% rownames(a2), a2[rownames(a2)=="Time",1], 0)
  
  # Treat in Days*Times
  # a3 <- anova(lm(y~Day+Time+Treat, data=design.Z))
  # DF_Treat.Runs <- ifelse("Treat" %in% rownames(a3), a3[rownames(a3)=="Treat",1], 0)
  
  # Results
  df <- c(LOF.Day.Treat_in_Runs=LOF.Day.Treat_in_Runs,
          PE.Day=PE.Day, total.Day=total.Day,
          LOF.Time.Treat_in_Runs=LOF.Time.Treat_in_Runs,
          PE.Time=PE.Time,total.Time=total.Time,
          DF_Treat.Runs=DF_Treat.Runs, Npar=Npar,
          LOF.Runs=LOF.Runs, PE.Runs=PE.Runs,
          total.Runs=N-(total.Day+total.Time+1),
          total=N-1, df_Treat.Full=df_Treat.Full, 
          N_Treat.Full=N_Treat.Full)
  return(df)
}

# Function to calculate D_S and A_S values for given variance component ratios
efficiencyAD <- function(design, K, Z1, Z2, model, Npar, sigma)
{
  W <- rep(1,Npar)   # weigths for the terms in the polynomial model
  W[(K+1):(2*K)] <- 0.25    # weights for quadratic terms
  W <- W/sum(W)
  design <- as.data.frame(design)
  res <- numeric(0)
  for(i in 1:nrow(sigma)){
    sig <- sigma[i,]
    V <- diag(rep(1,N))+sig[1]*(Z1%*%t(Z1))+sig[2]*(Z2%*%t(Z2))
    X <- model.matrix(model, data=design, keep.order=TRUE)
    Vi <- solve(V)
    V <- solve(t(X)%*%Vi%*%X) # 
    d <- round(det(V[-1,-1])^(1/Npar), 6)
    v <- sum(W*matrix(diag(V)[-1],nc=1))/sum(W)
    res <- rbind(res,c(d,v))
  }
  colnames(res) <- c("D", "A")
  return(res)
}
```

```{r}
K <- 3   # Total number of factors

# Design structure
m1 <- 7 # Days
m2 <- 4 # Times
b <- m1*m2
bsize <- 1

# Create unit factors
design.Z <- data.frame(Day=factor(rep(1:m1, rep(m2*bsize,m1))), 
                       Time=factor(rep(rep(1:m2,rep(bsize,m2)),m1)))

# Create matrices Z's
Z1 <- model.matrix(~-1+Day, data=design.Z)
Z2 <- model.matrix(~-1+Time, data=design.Z) 
N <- b*bsize

# Approximating model for treatment factors in all strata
model <- formula(~ X1+X2+X3+I(X1^2)+I(X2^2)+I(X3^2)+X1:X2+
                   X1:X3+X2:X3)
# p-1
Npar <- length(attr(terms(model), "term.labels")) 
```


```{r, warning=FALSE}
library(Matrix)
library(readr)
library(dplyr, warn.conflicts = FALSE)
library(digest)
library(ggplot2)
library(xtable)

# Read D*
jmp <- read_delim("EX1_JMP.csv", show_col_types = FALSE)
jmp <- jmp[,-c(1:2)]
df_jmp <- suppressWarnings(anovaDF(jmp, design.Z, Z1, Z2, Npar))

# Read MSS_D
d <- read_delim("EX1_D.csv", show_col_types = FALSE)
d <- d[,-c(1:2)]
df_mssd <- suppressWarnings(anovaDF(d, design.Z, Z1, Z2, Npar))

# Read MSS_DP
dp <- read_delim("EX1_DP.csv", show_col_types = FALSE)
dp <- dp[,-c(1:2)]
df_mssdp <- suppressWarnings(anovaDF(dp, design.Z, Z1, Z2, Npar))

# Read MSS_DP
cp <- read_delim("EX1_CP.csv", show_col_types = FALSE)
cp <- cp[,-c(1:2)]
df_msscp <- suppressWarnings(anovaDF(cp, design.Z, Z1, Z2, Npar))

# Read Mw
mw <- read_delim("EX1_Mw.csv", show_col_types = FALSE)
mw <- mw[,-c(1:2)]
df_mw <- suppressWarnings(anovaDF(mw, design.Z, Z1, Z2, Npar))
```
```{r, results='asis', echo=FALSE}
# results
source <- data.frame(names(df_jmp))
tab <- data.frame(t(rbind(df_jmp, df_mssd, df_mssdp, df_msscp, df_mw)))
row.names(tab) <- NULL
tab <- cbind(source, tab)[-((nrow(tab)-1):nrow(tab)),]
xtable_tab1 <- xtable(tab, digits=0, caption="Skeleton ANOVA of designs for Example 1")
colnames(xtable_tab1) <- c("Source", "D*", "MSSD","MSSDP","MSSCP", "Mw")
print(xtable_tab1, caption.placement = "top", 
      sanitize.colnames.function = identity, 
      hline.after = c(-1, 0, 3, 6, 11), include.rownames = FALSE, 
      comment = FALSE)
```
\setcounter{table}{1}
\captionsetup[table]{labelformat=S}
```{r, results='asis'}
# Efficiencies 
sig <- scan(text="1 10 100",what=double())
Sigma <- expand.grid(sig, sig)
Sigma <- Sigma[order(Sigma[,1],Sigma[,2]),]
sigma <- as.matrix(Sigma)
colnames(sigma) <- NULL
eff.jmp <- efficiencyAD(jmp, K, Z1, Z2, model, Npar, sigma)
eff.D <- efficiencyAD(d, K, Z1, Z2, model, Npar, sigma)
eff.DP <- efficiencyAD(dp, K, Z1, Z2, model, Npar, sigma)
eff.CP <- efficiencyAD(cp, K, Z1, Z2, model, Npar, sigma)
eff.mw <- efficiencyAD(mw, K, Z1, Z2, model, Npar, sigma)
eff <- cbind(eff.jmp, eff.D, eff.DP, eff.CP, eff.mw)
even_indexes<- seq(2,ncol(eff),2)
odd_indexes<- seq(1,ncol(eff),2)
resA <- eff[,even_indexes]
resD <- eff[,odd_indexes]
effD <- round(100*matrix(rep(resD[,1],ncol(resD)),nc=ncol(resD))/resD,2)
effD <- effD[,-1]
effA <- round(100*matrix(rep(resA[,1],ncol(resA)),nc=ncol(resA))/resA,2)
effA <- effA[,-1]
tab <- cbind(Sigma,e1=NA, effD, e2=NA, effA)
xtable_tabF <- xtable(tab, digits=c(0, 0, 0, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2),
                      caption = "Ds- and Aw-efficiencies, 
                      relative to the best fixed-effects D design obtained, 
                      given vc ratios, for designs for Example 1.")
colnames(xtable_tabF) <- c("eta1", "eta2", "", "D*", "MSSDP", "MSSCP", 
                           "Mw","", "D*", "MSSDP", "MSSCP", "Mw")
print(xtable_tabF, caption.placement = "top", include.rownames = FALSE, 
      comment = FALSE, add.to.row = list(pos = list(-1), 
      command = c("\\multicolumn{2}{c}{}&&\\multicolumn{4}{c}{Ds}&&
              \\multicolumn{4}{c}{Aw} \\\\  \n")))
```
\setcounter{figure}{2}
```{r, echo=FALSE, fig.cap="Ds- and Aw-efficiencies, relative to the D* design, as function of variance component ratios for designs for Example 1."}
# Combine and filter data
d1 <- data.frame(crit = "D", eta1 = Sigma[,1], eta2 = log10(Sigma[,2]),
                 Design = factor(rep(c("MSSD", "MSSDP", "MSSCP", "Mw"), 
                                     rep(9, 4))), eff = c(effD))
d2 <- data.frame(crit = "A", eta1 = Sigma[,1], eta2 = log10(Sigma[,2]),
                 Design = factor(rep(c("MSSD", "MSSDP", "MSSCP", "Mw"), 
                                     rep(9, 4))), eff = c(effA))
d <- rbind(d1, d2)

# Set factor levels to control legend order
d$crit <- factor(d$crit, levels = c("D", "A"),
                 labels = c(expression(paste(D[S])),
                            expression(paste(A[w]))))

d$Design <- factor(d$Design, levels = c("MSSD", "MSSDP", "MSSCP", "Mw"))


custom_colors <- c("MSSD" = "green", "MSSDP" = "pink", "MSSCP" = "black", "Mw"="#1F75FB")
custom_shapes <- c("MSSD" = 8, "MSSDP" = 15, "MSSCP" = 19, "Mw"=17)

labels <- c("MSSD" = expression(MSS[D[S]]),
            "MSSDP" = expression(MSS[paste("(", DP, ")"[S])]),
            "MSSCP" = expression(MSS[CP[kappa]]),
            "Mw"=expression(M[w]))

p <- ggplot(d, aes(log10(eta1), eff, group = interaction(eta2, Design), color = Design, shape=Design, linetype = factor(eta2))) + 
  facet_wrap(~crit, labeller = label_parsed) + 
  geom_point(size=2.5) +
  geom_line() + 
  scale_shape_manual(values = custom_shapes, labels = labels) +
  scale_color_manual(values = custom_colors, labels = labels) +
  labs(title = "", x = expression(log[10](eta[Days])), y = "Efficiency") + 
  scale_x_continuous(breaks = unique(log10(d$eta1))) + 
  guides(color = guide_legend(title = "Design: ", order=1), 
         shape = guide_legend(title = "Design: ", order=1),
  linetype = guide_legend(title = expression(log[10](eta[Times])*": ")), order=2) + 
  theme(axis.line = element_line(colour = "black"), panel.background = element_blank(), 
        legend.key = element_rect(fill = "transparent", color = NA),
        strip.background = element_rect(colour = NA, fill = NA),
        plot.background = element_rect(fill = NA, color = NA),
        legend.background = element_rect(fill = "transparent", color = NA),
        legend.box.background = element_rect(fill = "transparent", 
                                             color = NA),

        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        axis.text = element_text(size = 14),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16),
        strip.text = element_text(size = 16),
    legend.key.size = unit(1.5, "lines"),
    legend.spacing.x = unit(1, "cm"),
    legend.position = "bottom"
  )
p
```





