---
title: "Reproduction of Results for Example 4"
author: ""
date: ""
output:
  pdf_document:
    keep_tex: true
    fig_caption: true
header-includes:
  - \usepackage{caption}
  - \usepackage{amsmath}
  - \usepackage{graphicx}
  - \usepackage{enumitem}
  - \DeclareCaptionLabelFormat{S}{Table~S#2}
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=F}
# Function to assign labels to treatments
TreatLabelsFast <- function(X) {
  # Create a hash for each row
  hashes <- apply(X, 1, function(row) digest(row, algo = "xxhash64"))
  # Assign unique labels based on hash
  Treat <- as.numeric(factor(hashes))
  # Combine labels with original data
  Treat <- cbind(Treat, X)
  list(Treat = Treat)
}

# Function for DF breakdown
anovaDF <- function(design, design.Z, Z1, Z2, Z3, Npar.total, Npar.batch, Npar.occ, Npar.batchocc, Npar.Runs )
{
  N <- nrow(design)
  design <- design[,-c(1,9,14)]
  # Treatment factors
  # Full
  design.Z$Treat <- factor(TreatLabels(design,N)$Treat[,1])
  TFull  <- model.matrix(~-1+Treat, data=design.Z)
  N_Treat.Full <- rankMatrix(TFull)[1] # nlevels(design.Z$Treat)
  
  # Batch
  total.Batch <- nlevels(design.Z$batch)-1
  design.Z$t1 <- factor(TreatLabels(design[,1:7],N)$Treat[,1])
  T1  <- model.matrix(~-1+t1, data=design.Z)
  DF_Treat.Batch <- rankMatrix(T1)[1]-1
  
  # Occ
  total.Occ <- nlevels(design.Z$occ)-1
  design.Z$t2 <- factor(TreatLabels(design[,8:11],N)$Treat[,1])
  T2  <- model.matrix(~-1+t2, data=design.Z)
  DF_Treat.Occ <- rankMatrix(T2)[1]-1
  
  # Batch*Occ
  total.BatchOcc <- total.Batch*total.Occ
  design.Z$t3 <- factor(TreatLabels(design[,1:11],N)$Treat[,1])
  T3  <- model.matrix(~-1+t3, data=design.Z)
  DF_Treat.BatchOcc <- rankMatrix(T3)[1]-1-(DF_Treat.Occ+DF_Treat.Batch)
  
  # Runs
  total.Runs=N-(total.Batch+total.Occ+total.BatchOcc+1)
  B <- cbind(Z1,Z2,Z3)
  F <- cbind(B,TFull)
  DF_Treat.Runs <- rankMatrix(F)[1] - rankMatrix(B)[1]

  # PE and LOF
  # Batch
  PE.Batch <- rankMatrix(cbind(TFull,Z1,Z2))[1]-rankMatrix(cbind(TFull,Z2))[1]
  LOF.Batch <- DF_Treat.Batch-Npar.batch 
  LOF.Batch.Treat_in_Runs <- total.Batch-(DF_Treat.Batch+PE.Batch)
  # Occ
  PE.Occ <- rankMatrix(cbind(TFull,Z1,Z2))[1]-rankMatrix(cbind(TFull,Z1))[1]
  LOF.Occ <- DF_Treat.Occ-Npar.occ 
  LOF.Occ.Treat_in_Runs <- total.Occ-(DF_Treat.Occ+PE.Occ)
  # Batch*Occ
  PE.BatchOcc <- rankMatrix(cbind(TFull,Z1,Z2,Z3))[1]-
    rankMatrix(cbind(TFull,Z1,Z2))[1]
  LOF.BatchOcc <- DF_Treat.BatchOcc-Npar.batchocc 
  LOF.BatchOcc.Treat_in_Runs <- total.BatchOcc-(DF_Treat.BatchOcc+PE.BatchOcc)
  
  # Runs
  PE.Runs <- N - rankMatrix(F)[1]
  LOF.Runs <- DF_Treat.Runs-Npar.Runs
  
  # DF as sum of others DF
  df_Treat.Full=(DF_Treat.Batch+DF_Treat.Occ +  DF_Treat.BatchOcc + 
                   DF_Treat.Runs +   LOF.Batch.Treat_in_Runs + 
                   LOF.Occ.Treat_in_Runs + LOF.BatchOcc.Treat_in_Runs)
  
  df <- c(DF_Treat.Batch=DF_Treat.Batch, 
          Npar.batch=Npar.batch, 
          LOF.Batch=LOF.Batch,
          LOF.Batch.Treat_in_Runs=LOF.Batch.Treat_in_Runs,
          PE.Batch=PE.Batch, 
          total.Batch=total.Batch, 
          DF_Treat.Occ=DF_Treat.Occ, 
          Npar.occ=Npar.occ,
          LOF.Occ=LOF.Occ,
          LOF.Occ.Treat_in_Runs=LOF.Occ.Treat_in_Runs,
          PE.Occ=PE.Occ,
          total.Occ=total.Occ,
          DF_Treat.BatchOcc=DF_Treat.BatchOcc,
          Npar.batchocc=Npar.batchocc,
          LOF.BatchOcc=LOF.BatchOcc,
          LOF.BatchOcc.Treat_in_Runs=LOF.BatchOcc.Treat_in_Runs,
          PE.BatchOcc=PE.BatchOcc,
          total.BatchOcc=total.BatchOcc,
          DF_Treat.Runs=DF_Treat.Runs, 
          Npar.Runs=Npar.Runs,
          LOF.Runs=LOF.Runs, 
          PE.Runs=PE.Runs,
          total.Runs=total.Runs,
          total=N-1, N_Treat.Full=N_Treat.Full, 
          df_Treat.Full=df_Treat.Full)
  return(df)
}

# Function to calculate D_S and A_S values for given variance component ratios
efficiencyAD <- function(design, Z1, Z2, Z3, model, Npar, sigma)
{
  W <- rep(1,Npar)
  W[17:31] <- 0.25
  W <- W/sum(W)
  design <- as.data.frame(design)
  design <- design[,-c(1,9,14)]
  res <- numeric(0)
  for(i in 1:nrow(sigma)){
    sig <- sigma[i,]
    V <- diag(rep(1,N))+sig[1]*(Z1%*%t(Z1))+sig[2]*Z2%*%t(Z2)+
      sig[3]*Z3%*%t(Z3)
    X <- model.matrix(model, data=design, keep.order=TRUE)
    Vi <- solve(V)
    V <- solve(t(X)%*%Vi%*%X) # 
    d <- exp(sum(log(round(eigen(V[-1,-1], symmetric=TRUE, 
                                 only.values=TRUE)$values, 6)))/Npar)
    
    v <- sum(W*matrix(diag(V)[-1],nc=1))/sum(W)
    res <- rbind(res,c(d,v))
  }
  colnames(res) <- c("D", "A")
  return(res)
}
```

```{r echo=FALSE}
m1 <- 20 # batches
m2 <- 5 # occ
b <- m1*m2
bsize <- 5
design.Z <- data.frame(batch=factor(rep(1:m1, rep(m2*bsize,m1))), occ=factor(rep(rep(1:m2,rep(bsize,m2)),m1)), batch.occ=factor(rep(1:b,rep(bsize,b))))
Z1 <- model.matrix(~-1+batch, data=design.Z)
Z2 <- model.matrix(~-1+occ, data=design.Z) 
Z3 <- model.matrix(~-1+batch.occ, data=design.Z)                                                   
N <- b*bsize
# Approximating model in all strata
model <- formula(~ X1+X2+X3+X4+X5+X6+X7+
                   X8+X9+X10+X11+
                   X12+X13+X14+X15+X16+I(X12^2)+I(X13^2)+I(X14^2)+
                   I(X8*X12^2)+I(X8*X13^2)+I(X8*X14^2)+
                   I(X9*X12^2)+I(X9*X13^2)+I(X9*X14^2)+
                   I(X10*X12^2)+I(X10*X13^2)+I(X10*X14^2)+
                   I(X11*X12^2)+I(X11*X13^2)+I(X11*X14^2)+
                   X1:X2+X1:X3+X1:X4+X1:X5+X1:X6+X1:X7+
                   X1:X8+X1:X9+X1:X10+X1:X11+
                   X2:X8+X2:X9+X2:X10+X2:X11+
                   X3:X8+X3:X9+X3:X10+X3:X11+
                   X4:X8+X4:X9+X4:X10+X4:X11+
                   X5:X8+X5:X9+X5:X10+X5:X11+
                   X6:X8+X6:X9+X6:X10+X6:X11+
                   X7:X8+X7:X9+X7:X10+X7:X11+
                   X1:X2:X8+X1:X3:X8+X1:X4:X8+X1:X5:X8+X1:X6:X8+X1:X7:X8+
                   X1:X2:X9+X1:X3:X9+X1:X4:X9+X1:X5:X9+X1:X6:X9+X1:X7:X9+
                   X1:X2:X10+X1:X3:X10+X1:X4:X10+X1:X5:X10+X1:X6:X10+
                   X1:X7:X10+X1:X2:X11+X1:X3:X11+X1:X4:X11+X1:X5:X11+
                   X1:X6:X11+X1:X7:X11+
                   X1:X12+X1:X13+X1:X14+X1:X15+X1:X16+
                   X2:X12+X2:X13+X2:X14+X2:X15+X2:X16+
                   X3:X12+X3:X13+X3:X14+X3:X15+X3:X16+
                   X4:X12+X4:X13+X4:X14+X4:X15+X4:X16+
                   X5:X12+X5:X13+X5:X14+X5:X15+X5:X16+
                   X6:X12+X6:X13+X6:X14+X6:X15+X6:X16+
                   X7:X12+X7:X13+X7:X14+X7:X15+X7:X16+
                   X8:X12+X8:X13+X8:X14+X8:X15+X8:X16+
                   X9:X12+X9:X13+X9:X14+X9:X15+X9:X16+
                   X10:X12+X10:X13+X10:X14+X10:X15+X10:X16+
                   X11:X12+X11:X13+X11:X14+X11:X15+X11:X16+
                   X12:X13+X12:X14+X12:X15+X12:X16+
                   X13:X14+X13:X15+X13:X16+
                   X14:X15+X14:X16+
                   X1:X8:X12+X1:X8:X13+X1:X8:X14+X1:X8:X15+X1:X8:X16+
                   X1:X9:X12+X1:X9:X13+X1:X9:X14+X1:X9:X15+X1:X9:X16+  
                   X1:X10:X12+X1:X10:X13+X1:X10:X14+X1:X10:X15+X1:X10:X16+  
                   X1:X11:X12+X1:X11:X13+X1:X11:X14+X1:X11:X15+X1:X11:X16+
                   X2:X8:X12+X2:X8:X13+X2:X8:X14+X2:X8:X15+X2:X8:X16+
                   X2:X9:X12+X2:X9:X13+X2:X9:X14+X2:X9:X15+X2:X9:X16+
                   X2:X10:X12+X2:X10:X13+X2:X10:X14+X2:X10:X15+X2:X10:X16+
                   X2:X11:X12+X2:X11:X13+X2:X11:X14+X2:X11:X15+X2:X11:X16+
                   X3:X8:X12+X3:X8:X13+X3:X8:X14+X3:X8:X15+X3:X8:X16+
                   X3:X9:X12+X3:X9:X13+X3:X9:X14+X3:X9:X15+X3:X9:X16+
                   X3:X10:X12+X3:X10:X13+X3:X10:X14+X3:X10:X15+X3:X10:X16+
                   X3:X11:X12+X3:X11:X13+X3:X11:X14+X3:X11:X15+X3:X11:X16+
                   X4:X8:X12+X4:X8:X13+X4:X8:X14+X4:X8:X15+X4:X8:X16+
                   X4:X9:X12+X4:X9:X13+X4:X9:X14+X4:X9:X15+X4:X9:X16+
                   X4:X10:X12+X4:X10:X13+X4:X10:X14+X4:X10:X15+X4:X10:X16+
                   X4:X11:X12+X4:X11:X13+X4:X11:X14+X4:X11:X15+X4:X11:X16+
                   X5:X8:X12+X5:X8:X13+X5:X8:X14+X5:X8:X15+X5:X8:X16+
                   X5:X9:X12+X5:X9:X13+X5:X9:X14+X5:X9:X15+X5:X9:X16+
                   X5:X10:X12+X5:X10:X13+X5:X10:X14+X5:X10:X15+X5:X10:X16+
                   X5:X11:X12+X5:X11:X13+X5:X11:X14+X5:X11:X15+X5:X11:X16+
                   X6:X8:X12+X6:X8:X13+X6:X8:X14+X6:X8:X15+X6:X8:X16+
                   X6:X9:X12+X6:X9:X13+X6:X9:X14+X6:X9:X15+X6:X9:X16+
                   X6:X10:X12+X6:X10:X13+X6:X10:X14+X6:X10:X15+X6:X10:X16+
                   X6:X11:X12+X6:X11:X13+X6:X11:X14+X6:X11:X15+X6:X11:X16+
                   X7:X8:X12+X7:X8:X13+X7:X8:X14+X7:X8:X15+X7:X8:X16+
                   X7:X9:X12+X7:X9:X13+X7:X9:X14+X7:X9:X15+X7:X9:X16+
                   X7:X10:X12+X7:X10:X13+X7:X10:X14+X7:X10:X15+X7:X10:X16+
                   X7:X11:X12+X7:X11:X13+X7:X11:X14+X7:X11:X15+X7:X11:X16+
                   X8:X12:X13+X8:X12:X14+X8:X12:X15+X8:X12:X16+
                   X8:X13:X14+X8:X13:X15+X8:X13:X16+
                   X8:X14:X15+X8:X14:X16+
                   X9:X12:X13+X9:X12:X14+X9:X12:X15+X9:X12:X16+
                   X9:X13:X14+X9:X13:X15+X9:X13:X16+
                   X9:X14:X15+X9:X14:X16+
                   X10:X12:X13+X10:X12:X14+X10:X12:X15+X10:X12:X16+
                   X10:X13:X14+X10:X13:X15+X10:X13:X16+
                   X10:X14:X15+X10:X14:X16+
                   X11:X12:X13+X11:X12:X14+X11:X12:X15+X11:X12:X16+
                   X11:X13:X14+X11:X13:X15+X11:X13:X16+
                   X11:X14:X15+X11:X14:X16)
Npar <- length(attr(terms(model), "term.labels")) 

model.occ <- formula(~ X8+X9+X10+X11)
Npar.occ <- length(attr(terms(model.occ), "term.labels")) 

model.occ.batch <- formula(~X1:X8+X1:X9+X1:X10+X1:X11+
                   X2:X8+X2:X9+X2:X10+X2:X11+
                   X3:X8+X3:X9+X3:X10+X3:X11+
                   X4:X8+X4:X9+X4:X10+X4:X11+
                   X5:X8+X5:X9+X5:X10+X5:X11+
                   X6:X8+X6:X9+X6:X10+X6:X11+
                   X7:X8+X7:X9+X7:X10+X7:X11+
                   X1:X2:X8+X1:X3:X8+X1:X4:X8+X1:X5:X8+X1:X6:X8+X1:X7:X8+
                   X1:X2:X9+X1:X3:X9+X1:X4:X9+X1:X5:X9+X1:X6:X9+X1:X7:X9+
                   X1:X2:X10+X1:X3:X10+X1:X4:X10+X1:X5:X10+X1:X6:X10+
                   X1:X7:X10+X1:X2:X11+X1:X3:X11+X1:X4:X11+X1:X5:X11+
                   X1:X6:X11+X1:X7:X11)

Npar.batchocc <- length(attr(terms(model.occ.batch), "term.labels")) 

# Approximating model in the lower stratum (Runs)
model.Runs <- formula(~X12+X13+X14+X15+X16+I(X12^2)+I(X13^2)+I(X14^2)+
                   I(X8*X12^2)+I(X8*X13^2)+I(X8*X14^2)+
                   I(X9*X12^2)+I(X9*X13^2)+I(X9*X14^2)+
                   I(X10*X12^2)+I(X10*X13^2)+I(X10*X14^2)+
                   I(X11*X12^2)+I(X11*X13^2)+I(X11*X14^2)+
                   X1:X12+X1:X13+X1:X14+X1:X15+X1:X16+
                   X2:X12+X2:X13+X2:X14+X2:X15+X2:X16+
                   X3:X12+X3:X13+X3:X14+X3:X15+X3:X16+
                   X4:X12+X4:X13+X4:X14+X4:X15+X4:X16+
                   X5:X12+X5:X13+X5:X14+X5:X15+X5:X16+
                   X6:X12+X6:X13+X6:X14+X6:X15+X6:X16+
                   X7:X12+X7:X13+X7:X14+X7:X15+X7:X16+
                   X8:X12+X8:X13+X8:X14+X8:X15+X8:X16+
                   X9:X12+X9:X13+X9:X14+X9:X15+X9:X16+
                   X10:X12+X10:X13+X10:X14+X10:X15+X10:X16+
                   X11:X12+X11:X13+X11:X14+X11:X15+X11:X16+
                   X12:X13+X12:X14+X12:X15+X12:X16+
                   X13:X14+X13:X15+X13:X16+
                   X14:X15+X14:X16+
                   X1:X8:X12+X1:X8:X13+X1:X8:X14+X1:X8:X15+X1:X8:X16+
                   X1:X9:X12+X1:X9:X13+X1:X9:X14+X1:X9:X15+X1:X9:X16+  
                   X1:X10:X12+X1:X10:X13+X1:X10:X14+X1:X10:X15+X1:X10:X16+  
                   X1:X11:X12+X1:X11:X13+X1:X11:X14+X1:X11:X15+X1:X11:X16+
                   X2:X8:X12+X2:X8:X13+X2:X8:X14+X2:X8:X15+X2:X8:X16+
                   X2:X9:X12+X2:X9:X13+X2:X9:X14+X2:X9:X15+X2:X9:X16+
                   X2:X10:X12+X2:X10:X13+X2:X10:X14+X2:X10:X15+X2:X10:X16+
                   X2:X11:X12+X2:X11:X13+X2:X11:X14+X2:X11:X15+X2:X11:X16+
                   X3:X8:X12+X3:X8:X13+X3:X8:X14+X3:X8:X15+X3:X8:X16+
                   X3:X9:X12+X3:X9:X13+X3:X9:X14+X3:X9:X15+X3:X9:X16+
                   X3:X10:X12+X3:X10:X13+X3:X10:X14+X3:X10:X15+X3:X10:X16+
                   X3:X11:X12+X3:X11:X13+X3:X11:X14+X3:X11:X15+X3:X11:X16+
                   X4:X8:X12+X4:X8:X13+X4:X8:X14+X4:X8:X15+X4:X8:X16+
                   X4:X9:X12+X4:X9:X13+X4:X9:X14+X4:X9:X15+X4:X9:X16+
                   X4:X10:X12+X4:X10:X13+X4:X10:X14+X4:X10:X15+X4:X10:X16+
                   X4:X11:X12+X4:X11:X13+X4:X11:X14+X4:X11:X15+X4:X11:X16+
                   X5:X8:X12+X5:X8:X13+X5:X8:X14+X5:X8:X15+X5:X8:X16+
                   X5:X9:X12+X5:X9:X13+X5:X9:X14+X5:X9:X15+X5:X9:X16+
                   X5:X10:X12+X5:X10:X13+X5:X10:X14+X5:X10:X15+X5:X10:X16+
                   X5:X11:X12+X5:X11:X13+X5:X11:X14+X5:X11:X15+X5:X11:X16+
                   X6:X8:X12+X6:X8:X13+X6:X8:X14+X6:X8:X15+X6:X8:X16+
                   X6:X9:X12+X6:X9:X13+X6:X9:X14+X6:X9:X15+X6:X9:X16+
                   X6:X10:X12+X6:X10:X13+X6:X10:X14+X6:X10:X15+X6:X10:X16+
                   X6:X11:X12+X6:X11:X13+X6:X11:X14+X6:X11:X15+X6:X11:X16+
                   X7:X8:X12+X7:X8:X13+X7:X8:X14+X7:X8:X15+X7:X8:X16+
                   X7:X9:X12+X7:X9:X13+X7:X9:X14+X7:X9:X15+X7:X9:X16+
                   X7:X10:X12+X7:X10:X13+X7:X10:X14+X7:X10:X15+X7:X10:X16+
                   X7:X11:X12+X7:X11:X13+X7:X11:X14+X7:X11:X15+X7:X11:X16+
                   X8:X12:X13+X8:X12:X14+X8:X12:X15+X8:X12:X16+
                   X8:X13:X14+X8:X13:X15+X8:X13:X16+
                   X8:X14:X15+X8:X14:X16+
                   X9:X12:X13+X9:X12:X14+X9:X12:X15+X9:X12:X16+
                   X9:X13:X14+X9:X13:X15+X9:X13:X16+
                   X9:X14:X15+X9:X14:X16+
                   X10:X12:X13+X10:X12:X14+X10:X12:X15+X10:X12:X16+
                   X10:X13:X14+X10:X13:X15+X10:X13:X16+
                   X10:X14:X15+X10:X14:X16+
                   X11:X12:X13+X11:X12:X14+X11:X12:X15+X11:X12:X16+
                   X11:X13:X14+X11:X13:X15+X11:X13:X16+
                   X11:X14:X15+X11:X14:X16)
Npar.Runs <- length(attr(terms(model.Runs), "term.labels"))
Npar.batch <- Npar-(Npar.occ+Npar.batchocc+Npar.Runs)
```

```{r, warning=FALSE}
library(Matrix)
library(readr)
library(dplyr, warn.conflicts = FALSE)
library(digest)
library(ggplot2)
library(xtable)
# load the MSS designs
D <- read_delim("EX4_MSSD.csv", show_col_types = FALSE)
df_D <- suppressWarnings(anovaDF(D, design.Z, Z1, Z2, Z3, Npar.total, Npar.batch, 
                                 Npar.occ, Npar.batchocc, Npar.Runs))
DP <- read_delim("EX4_MSSDP.csv", show_col_types = FALSE)
df_DP <- suppressWarnings(anovaDF(DP, design.Z, Z1, Z2, Z3, Npar.total, Npar.batch, 
                                  Npar.occ, Npar.batchocc, Npar.Runs))
CP <- read_delim("EX4_MSSCP.csv", show_col_types = FALSE)
df_CP <- suppressWarnings(anovaDF(CP, design.Z, Z1, Z2, Z3, Npar.total, Npar.batch, 
                                  Npar.occ, Npar.batchocc, Npar.Runs))
```

\setcounter{table}{3}
```{r, results='asis', echo=FALSE}
# results
source <- data.frame(names(df_D))
tab <- data.frame(t(rbind(df_D, df_DP, df_CP)))
row.names(tab) <- NULL
tab <- cbind(source, tab)
xtable_tab4 <- xtable(tab, digits=0, caption="Skeleton ANOVA of designs for Example 4")
colnames(xtable_tab4) <- c("Source", "MSSD","MSSDP","MSSCP")
print(xtable_tab4, caption.placement = "top", 
      sanitize.colnames.function = identity, 
      hline.after = c(-1, 0, 6, 12, 16, 18), include.rownames = FALSE, 
      comment = FALSE)
```
\setcounter{table}{6}
\captionsetup[table]{labelformat=S}
```{r, results='asis', echo=FALSE}
# Efficiencies
sig <- scan(text="1 10 100",what=double())
Sigma <- expand.grid(sig, sig, sig)
Sigma <- Sigma[order(Sigma[,1],Sigma[,2],Sigma[,3]),]
sigma <- as.matrix(Sigma)
colnames(sigma) <- NULL
eff.D <- efficiencyAD(D, Z1, Z2, Z3, model, Npar, sigma)
eff.DP <- efficiencyAD(DP, Z1, Z2, Z3, model, Npar, sigma)
eff.CP <- efficiencyAD(CP, Z1, Z2, Z3, model, Npar, sigma)
eff <- cbind(eff.D, eff.DP, eff.CP)
even_indexes<- seq(2,ncol(eff),2)
odd_indexes<- seq(1,ncol(eff),2)
resA <- eff[,even_indexes]
resD <- eff[,odd_indexes]
effD <- round(100*matrix(rep(resD[,1],ncol(resD)),nc=ncol(resD))/resD,2)
effD <- effD[,-1]
effA <- round(100*matrix(rep(resA[,1],ncol(resA)),nc=ncol(resA))/resA,2)
effA <- effA[,-1]
tab <- cbind(Sigma,e1=NA, effD, e2=NA, effA)
library(xtable)
xtable_tabF <- xtable(tab, digits=c(0, 0, 0, 0, 2, 2, 2, 2, 2, 2),
                      caption = "(Ds- and Aw-efficiencies, relative to the MSSD optimum design, given vc, for designs for Example 4.")
colnames(xtable_tabF) <- c("eta1", "eta2", "eta3", "", "MSSDP", "MSSCP", "",
                           "MSSDP", "MSSCP")
print(xtable_tabF, caption.placement = "top", include.rownames = FALSE, 
      comment = FALSE, add.to.row = list(pos = list(-1), 
                                         command = c("\\multicolumn{3}{c}{}&&\\multicolumn{2}{c}{Ds}&&\\multicolumn{2}{c}{Aw} \\\\  \n")))
```


\setcounter{figure}{8}
```{r, echo=FALSE, fig.cap="Ds and Aw efficiencies, relative to the MSSD design, as function of variance component ratios for designs for Example 4."}
# Combine and filter data
library(ggplot2)

# Combine and filter data
d1 <- data.frame(crit = "D", eta1 = log10(Sigma[,1]), 
                 eta2 = log10(Sigma[,2]), eta3 = Sigma[,3], 
                 Design = factor(rep(c("MSSDP", "MSSCP"), rep(27, 2))), 
                 eff = c(effD))
d2 <- data.frame(crit = "A", eta1 = log10(Sigma[,1]), 
                 eta2 = log10(Sigma[,2]), eta3 = Sigma[,3], 
                 Design = factor(rep(c("MSSDP", "MSSCP"), rep(27, 2))),
                 eff = c(effA))
d3 <- rbind(d1, d2)
d <- d3[d3[,2]!=1&d3[,3]!=1,]

# Set factor levels to control legend order
d$crit <- factor(d$crit, levels = c("D", "A"),
                 labels = c(expression(paste(D[S])),
                            expression(paste(A[w]))))

d$Design <- factor(d$Design, levels = c("MSSDP", "MSSCP"))


custom_colors <- c("MSSDP" = "pink", "MSSCP" = "black")
custom_shapes <- c("MSSDP" = 15, "MSSCP" = 19)

labels <- c(
  "MSSDP" = expression(MSS["(DP)"[S]]),
  "MSSCP" = expression(MSS[CP[kappa]])
)

p <- ggplot(d, aes(log10(eta3), eff, group = interaction(eta1, eta2, Design), 
                   color = Design, shape=Design, 
                   linetype = factor(interaction(eta1,eta2)))) + 
  facet_wrap(~crit, labeller = label_parsed) + 
  geom_point(size=2.5) +
  geom_line() + 
  scale_shape_manual(values = custom_shapes, labels = labels) +
  scale_color_manual(values = custom_colors, labels = labels) +
  labs(title = "", x = expression(log[10](eta[Batches*paste("*")*Occs])), 
       y = "Efficiency") + 
  scale_x_continuous(breaks = unique(log10(d$eta3))) + 
  guides(color = guide_legend(title = "Design: ", order=1), 
         shape = guide_legend(title = "Design: ", order=1),
         linetype = guide_legend(
           title = expression(log10(eta[Batches])*paste(".")*log10(eta[Occs])*": "),
           order=2)) + 
  theme(axis.line = element_line(colour = "black"), 
        panel.background = element_blank(), 
        legend.key = element_rect(fill = "transparent", color = NA),
        strip.background = element_rect(colour = NA, fill = NA),
        plot.background = element_rect(fill = NA, color = NA),
        legend.background = element_rect(fill = "transparent", color = NA),
        legend.box.background = element_rect(fill = "transparent", color = NA),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        axis.text = element_text(size = 14),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16),
        strip.text = element_text(size = 16),
        legend.key.size = unit(1.5, "lines"),
        legend.spacing.x = unit(1, "cm"),
        legend.position = "bottom"
  )
p
```